apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: evolut-insurance
  namespace: log-pilot
  labels:
    k8s-app: evolut-insurance

spec:
  replicas: 1
  #滚动升级时70s后认为该pod就绪
  revisionHistoryLimit: 3
  minReadySeconds: 70
  strategy:
    ##由于replicas为3,则整个升级,pod个数在2-4个之间
    rollingUpdate:
      #滚动升级时会先启动1个pod    
      maxSurge: 1 
      #滚动升级时允许的最大Unavailable的pod个数      
      maxUnavailable: 1 
  selector:
    matchLabels:
      k8s-app: evolut-insurance
  template:
    metadata:
      labels:
        k8s-app: evolut-insurance
    spec:
      ##k8s将会给应用发送SIGTERM信号
      terminationGracePeriodSeconds: 60 
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      containers:
      - name: evolut-insurance
        image: 10.250.200.200/k8s/evolut-backend/evolut-insurance:V2.0-43
        env:
        - name: aliyun_logs_k9s-evolut-insurance
          value: "stdout"
        - name: aliyun_logs_k9s-evolut-insurance_format
          value: "json"
        - name: aliyun_logs_access
          value: "/opt/app/logs/evolut-insurance/evolut-insurance.log"
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            memory:  1024Mi
            #cpu: 1000m
          requests:
            memory:  1024Mi
            #cpu: 100m
        ports:
        #容器的端口
        - containerPort: 7005
          #name: ui
          protocol: TCP
        volumeMounts:
        - name: k9s-evolut-insurance
          mountPath: /opt/app/logs/
      volumes:
      - name: k9s-evolut-insurance
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: evolut-insurance
  namespace: log-pilot
  labels:
    k8s-app: evolut-insurance

spec:
  type: NodePort
  ports:
  #集群IP的端口
  - port: 7005
    protocol: TCP
    #容器的端口
    targetPort: 7005
    nodePort: 37777
  selector:
    k8s-app: evolut-insurance
