apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaisa-comm-system
  namespace: dev
  labels:
    k8s-app: kaisa-comm-system

spec:
  replicas: 1
  revisionHistoryLimit: 3
  #滚动升级时70s后认为该pod就绪
  minReadySeconds: 70
  strategy:
    ##由于replicas为3,则整个升级,pod个数在2-4个之间
    rollingUpdate:
      #滚动升级时会先启动1个pod
      maxSurge: 1
      #滚动升级时允许的最大Unavailable的pod个数
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kaisa-comm-system
  template:
    metadata:
      labels:
        k8s-app: kaisa-comm-system
    spec:
      #nodeSelector:
      #type: node244
      ##k8s将会给应用发送SIGTERM信号
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: harborsecret
      containers:
        - name: kaisa-comm-system
          image: 192.168.6.229/dev/kaisa-comm-system:V1.0-18
          imagePullPolicy: IfNotPresent
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              memory: 512Mi
              #cpu:  200m
            requests:
              #cpu: 100m
              memory: 512Mi
          ports:
            #容器的端口
            - containerPort: 7011
              #name: ui
              protocol: TCP
                ####监控检测########
                # livenessProbe:
                # httpGet:
                # path: /devZuul/info
                # port: 8005
                # scheme: HTTP
                # initialDelaySeconds: 180
                # timeoutSeconds: 5
                # periodSeconds: 15
                # successThreshold:  1
                # failureThreshold:  2
                # readinessProbe:
              # httpGet:
              # path: /devZuul/info
              # port: 8005
              # scheme: HTTP
              # initialDelaySeconds: 180
              # timeoutSeconds: 5
              # periodSeconds: 15
              # successThreshold:  1
              # failureThreshold:  2
          env:
          - name: aliyun_logs_kaisa-comm-system
            value: "/logs/kaisa/kaisa-comm-system.json"
          - name: aliyun_logs_kaisa-comm-system
            value: "stdout"
          #- name: aliyun_logs_kaisa-comm-system_format
             #value: "json"
          volumeMounts:
          - name: kaisa-comm-system
            mountPath: /logs/kaisa/
      volumes:
      - name: kaisa-comm-system
        hostPath:
          path: /logs/kaisa/kaisa-comm-system
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: kaisa-comm-system
  namespace: dev
  labels:
    k8s-app: kaisa-comm-system

spec:
  #type: NodePort
  ports:
    #集群IP的端口
    - port: 7011
      protocol: TCP
      targetPort: 7011
  #type: NodePort
  selector:
    k8s-app: kaisa-comm-system
