apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
      grafana_datasource: "true"
data:
  datasource.yml: |-
     apiVersion: 1
     datasources:
     - name: prometheus
       type: prometheus
       access: proxy
       orgId: 1
       url: http://prometheus-svc.monitoring.svc.cluster.local:9090
       isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: monitoring
  labels:
      grafana_dashboard: "true"
data:
  datasource.yml: |-
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
        options:
          path: /var/lib/grafana/dashboards/